const swaggerJsdoc = require("swagger-jsdoc");
const swaggerUi = require("swagger-ui-express");

const options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Products API",
      version: "1.0.0",
      description: "A simple Express.js API for managing products",
    },
    servers: [
      {
        url: "http://localhost:3000/api",
      },
    ],
    components: {
      schemas: {
        Product: {
          type: "object",
          properties: {
            productId: {
              type: "integer",
              description: "The product Id generated by the server.",
              example: 10,
            },
            productName: {
              type: "string",
              description: "The product name.",
              example: "Apple",
            },
            productOwnerName: {
              type: "string",
              description: "The product lead.",
              example: "Steve Jobs",
            },
            Developers: {
              type: "array",
              items: {
                type: "string",
              },
              description: "The product developers.",
              example: ["Steve Wozniak", "Chris Lattner"],
            },
            scrumMasterName: {
              type: "string",
              description: "The scrum facilitator.",
              example: "Brendan Eich",
            },
            startDate: {
              type: "string",
              format: "date",
              description: "The scrum facilitator.",
              example: "2022-10-10",
            },
            methodology: {
              type: "string",
              description: "(Agile or Waterfall).",
              example: "Agile",
            },
          },
        },
      },
    },
  },
  apis: ["./src/routes/*.js", "./src/routes/products/*.js"],
};

const specs = swaggerJsdoc(options);

module.exports = (app) => {
  app.use("/api/api-docs", swaggerUi.serve, swaggerUi.setup(specs));
};
